[project]
name = "pynovelspider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "pydantic>=2.10.6",
    "requests[socks]>=2.32.3",
]
